name: Deploy ASP.NET to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Restore Dependencies
        run: dotnet restore FreelancePlatform/FreelancePlatform.csproj

      - name: Build Project
        run: dotnet build FreelancePlatform/FreelancePlatform.csproj --configuration Release

      - name: Publish Project
        run: dotnet publish FreelancePlatform/FreelancePlatform.csproj --configuration Release --output publish

      - name: Deploy to Firebase Hosting
        run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
